apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager-issuer:
        email: walid.shaari@gmail.com
      configureCertmanager:
        install: false
      global:
        hosts: {}
        ingress:
          annotations:
            kubernetes.io/tls-acme: true
            route.openshift.io/termination: edge
          class: none
      nginx-ingress:
        enabled: false
    version: 8.0.0
