apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager-issuer:
        email: walid.shaari@gmail.com
      configureCertmanager:
        install: false
      global:
        hosts: 
          domain: apps.rosa.gm-2405171644.5f06.p3.openshiftapps.com
        ingress:
          annotations:
            kubernetes.io/tls-acme: true
            route.openshift.io/termination: edge
          class: none
      nginx-ingress:
        enabled: false
    version: 7.11.12
