- name: Gitlab setup
  hosts: localhost
  gather_facts: false
  vars:
    idp_namespace: "rhdh-demo"
    idp_instance_name: "redhat-developer-hub"
    git_system: "gitlab"
    gitlab_instance_name: "gitlab"
    gitlab_root_secret_name: "{{ gitlab_instance_name }}-gitlab-initial-root-password"
    gitlab_namespace: "gitlab-system"
    gitlab_host: ""
    vault_namespace: "vault"
    keycloak_host: ""
    backstage_gitops_repo: "https://github.com/RockStarDeveloperHub/redhat-developer-hub-gitops-bootstrap.git"

  tasks:
    - name: Retrieve Ingress config
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Ingress
        name: cluster
      register: r_ingress_config

    - name: Retrieve Infrastructure config
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: r_infra_config

    - name: Set OpenShift Cluster Domain and API URLs
      ansible.builtin.set_fact:
        apps_cluster_domain: "{{ r_ingress_config.resources[0].spec.domain }}"
        cluster_api_url: "{{ r_infra_config.resources[0].status.apiServerURL }}"

    - name: Set OpenShift Apps URLs
      ansible.builtin.set_fact:
        gitlab_host: "gitlab.gitlab-{{
          gitlab_namespace }}.{{
          apps_cluster_domain }}"
        keycloak_host: "keycloak-{{
          idp_namespace }}.{{
          apps_cluster_domain }}"
        backstage_host: "redhat-developer-hub-{{
          idp_namespace }}.{{
          apps_cluster_domain }}"
        devspaces_host: "devspaces.{{
          apps_cluster_domain }}"
        openshift_redirect_host: "oauth-openshift.{{
          apps_cluster_domain }}"
        openshift_console_host: console-openshift-console.{{
          apps_cluster_domain }}

    - name: Debug vars
      ansible.builtin.debug:
        msg:
          - "apps_cluster_domain: {{ apps_cluster_domain }}"
          - "cluster_api_url: {{ cluster_api_url }}"

    - name: Setup Gitlab dependencies
      ansible.builtin.include_tasks:
        file: ./setup_gitlab.yml
      when: git_system == "gitlab"
